<?php

return array(
	'version' => '0.9.4.1',
	'pgcache.enabled' => false,
	'pgcache.engine' => 'file_generic',
	'dbcache.enabled' => false,
	'dbcache.engine' => 'file',
	'objectcache.enabled' => false,
	'objectcache.engine' => 'file',
	'cdn.enabled' => false,
	'cdn.engine' => 'cf',
	'varnish.enabled' => false,
	'varnish.servers' => array(
		0 => '',
	),
	'widget.pagespeed.enabled' => true,
	'widget.pagespeed.key' => '',
	'config.check' => true,
	'cdn.debug' => true,
	'pgcache.file.nfs' => false,
	'minify.file.nfs' => false,
	'dbcache.file.locking' => false,
	'objectcache.file.locking' => false,
	'pgcache.file.locking' => false,
	'minify.file.locking' => false,
	'cdn.uploads.enable' => true,
	'cdn.includes.enable' => true,
	'cdn.theme.enable' => true,
	'cdn.custom.enable' => true,
	'cdn.force.rewrite' => false,
	'cdn.import.external' => false,
	'cdn.cf.key' => 'AKIAJSOZVDNYEWTXO2CQ',
	'cdn.cf.secret' => '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',
	'cdn.cf.bucket' => 'priyaj',
	'cdn.cf.ssl' => 'auto',
	'cdn.cf.id' => 'd28fzo85uc1fsk',
	'cdn.reject.ssl' => false,
	'cdn.reject.logged_roles' => false,
	'cdn.reject.roles' => array(
		0 => '',
	),
	'cdn.reject.uri' => array(
		0 => '',
	),
	'cdn.autoupload.enabled' => false,
	'cdn.autoupload.interval' => 3600,
	'cdn.queue.interval' => 900,
	'cdn.queue.limit' => 25,
	'cdn.includes.files' => '*.css;*.js;*.gif;*.png;*.jpg;*.xml',
	'cdn.theme.files' => '*.css;*.js;*.gif;*.png;*.jpg;*.ico;*.ttf;*.otf,*.woff,*.less',
	'cdn.import.files' => '',
	'cdn.custom.files' => array(
		0 => 'favicon.ico',
		1 => '{wp_content_dir}/gallery/*',
		2 => '{wp_content_dir}/uploads/avatars/*',
		3 => '{plugins_dir}/wordpress-seo/css/xml-sitemap.xsl',
		4 => '{plugins_dir}/wp-minify/min*',
		5 => '{plugins_dir}/*.js',
		6 => '{plugins_dir}/*.css',
		7 => '{plugins_dir}/*.gif',
		8 => '{plugins_dir}/*.jpg',
		9 => '{plugins_dir}/*.png',
	),
	'cdn.reject.ua' => array(
		0 => '',
	),
	'cdn.reject.files' => array(
		0 => '{uploads_dir}/wpcf7_captcha/*',
		1 => '{uploads_dir}/imagerotator.swf',
		2 => '{plugins_dir}/wp-fb-autoconnect/facebook-platform/channel.html',
	),
	'cdn.cf.cname' => array(
		0 => 'cdncss.glitzblitz.co.in',
		1 => 'cdnjs.glitzblitz.co.in',
	),
	'notes.cdn_upload' => true,
	'notes.need_empty_pgcache' => true,
	'pgcache.debug' => false,
	'dbcache.debug' => false,
	'objectcache.debug' => false,
	'varnish.debug' => false,
);